### ISSUE TITLE
[FEAT] MainView 구현 마무리하기

### ISSUE THREAD

**Issue by yujinnee** [SOPT-29th-Joint-Seminar-11/Tabling-iOS#22]
## 📌  Feature Issue

MainView 구현을 마무리하도록 하겠습니다.!
## 📝  To-do

- [x] Review CollectionView 구현하기
- [x] Review 담을 모델 구현하기
- [x] Store CollectionView 옵션 태그 구현하기
- [x] 광고 배너 셀 구현하기
- [x] 테이블뷰 라인 없애기
- [x] 컬렉션뷰 스크롤바 없애기
- [x] UI, 오토레이아웃 마무리 손보기
