### ISSUE TITLE
[FEAT] MainView 서버 연결

### ISSUE THREAD

**Issue by ningpop** [SOPT-29th-Joint-Seminar-11/Tabling-iOS#29]
## 📌  Feature Issue

MainView에 서버 연결을 해볼까 합니다!

## 📝  To-do

- [ ] Moya 활용법 익히기
- [x] 서버와 연결 후 response값 모델에 저장
- [x] 모델에 저장한 값을 MainView에 띄우기
