### ISSUE TITLE
[FEAT] DetailView Layout 큰 틀 잡기

### ISSUE THREAD

**Issue by heerucan** [SOPT-29th-Joint-Seminar-11/Tabling-iOS#9]
## 📌  Feature Issue
DetailView Layout 구현과 관련된 이슈입니다.
전반적인 틀을 먼저 잡으려고 합니다.

## 📝  To-do

- [x] mainTV (상단은 statusBar까지)
- [x] 상단 음식 collectionView 하나 넣어서 collectionCell 추가
- [x] 하단 부분 레이아웃 구현
